import type { ExpoConfig } from "expo/config";
import fs from "fs";
import { version } from "./package.json";

/**
 * EzySplit — Expo config (Android only).
 * android/ is GENERATED by `npx expo prebuild` — never edit it by hand.
 *
 * versionCode: Play requires each upload to exceed the last one. Old CI used
 * BUILD_NUMBER + 11. Set VERSION_CODE explicitly for the first Expo release
 * so it is higher than the current Play Console code.
 */
const BUILD_NUMBER = parseInt(process.env.BUILD_NUMBER || "1", 10);
const VERSION_CODE = process.env.VERSION_CODE
  ? parseInt(process.env.VERSION_CODE, 10)
  : BUILD_NUMBER + 11;

const FONTS = [
  "JetBrainsMono-Medium",
  "Manrope-Bold",
  "Manrope-ExtraBold",
  "Manrope-Medium",
  "Manrope-Regular",
  "Manrope-SemiBold",
  "Sora-Bold",
  "Sora-ExtraBold",
  "Sora-Regular",
  "Sora-SemiBold",
].map((f) => `./src/assets/fonts/${f}.ttf`);

const BG = "#0A0F1C";
// Single source of truth: package.json version is also what App.tsx writes
// to users/{uid}.appVersion and what the force-update gate compares.

/**
 * Two app variants from ONE codebase, each talking to its OWN Firebase project:
 *   prod (default)             com.techtitens.ezysplit      ./google-services.json  (esplit-d362c, LIVE users)
 *   APP_VARIANT=development    com.techtitens.ezysplit.dev  ./firebase/dev/google-services.json
 * Different package ids => both install side by side on one phone, and the
 * dev build can never read or write prod data.
 */
const IS_DEV = process.env.APP_VARIANT === "development";
const GOOGLE_SERVICES = IS_DEV
  ? "./firebase/dev/google-services.json"
  : "./google-services.json";
const GOOGLE_SERVICES_IOS = IS_DEV
  ? "./firebase/dev/GoogleService-Info.plist"
  : "./GoogleService-Info.plist";

// Dev builds get an orange "DEV" band on the icon so the two apps are
// easy to tell apart when both are installed (assets/dev/*).
const ICON = IS_DEV ? "./assets/dev/icon.png" : "./assets/icon.png";
const ANDROID_FOREGROUND = IS_DEV
  ? "./assets/dev/android-icon-foreground.png"
  : "./assets/android-icon-foreground.png";

// Google Sign-In needs the project's *web* OAuth client id (client_type 3),
// which is inside google-services.json once Google sign-in is enabled in
// that Firebase project - read it from there so each variant gets its own.
function googleWebClientId(): string | undefined {
  try {
    const json = JSON.parse(fs.readFileSync(GOOGLE_SERVICES, "utf8"));
    for (const client of json.client ?? []) {
      const web = (client.oauth_client ?? []).find(
        (o: { client_type: number }) => o.client_type === 3,
      );
      if (web) {
        return web.client_id;
      }
    }
  } catch {
    // missing file: prebuild will fail loudly on googleServicesFile anyway
  }
  return undefined;
}

const config: { expo: ExpoConfig } = {
  expo: {
    name: IS_DEV ? "EzySplit Dev" : "EzySplit",
    slug: "ezysplit",
    version,
    orientation: "portrait",
    icon: ICON,
    scheme: IS_DEV ? "ezysplit-dev" : "ezysplit",
    userInterfaceStyle: "dark",
    backgroundColor: BG,
    // web: for Arun's own quick testing only (not shipped to users).
    platforms: ["android", "ios", "web"],
    ios: {
      // Same bundle id + GoogleService-Info.plist as the CLI app's iOS target.
      bundleIdentifier: IS_DEV
        ? "com.techtitens.ezysplit.dev"
        : "com.techtitens.ezysplit",
      // Personal (free) team "Arun Kumar" - same DEVELOPMENT_TEAM as the CLI
      // app's Xcode project. Keeps signing set after every prebuild --clean.
      appleTeamId: "L2559D894B",
      buildNumber: String(VERSION_CODE),
      googleServicesFile: GOOGLE_SERVICES_IOS,
      supportsTablet: false,
      infoPlist: {
        // Linking.canOpenURL('whatsapp://...') for the invite sheet.
        LSApplicationQueriesSchemes: ["whatsapp"],
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    web: {
      favicon: "./assets/favicon.png",
      bundler: "metro",
    },
    android: {
      package: IS_DEV
        ? "com.techtitens.ezysplit.dev"
        : "com.techtitens.ezysplit",
      versionCode: VERSION_CODE,
      googleServicesFile: GOOGLE_SERVICES,
      adaptiveIcon: {
        foregroundImage: ANDROID_FOREGROUND,
        backgroundImage: "./assets/android-icon-background.png",
        backgroundColor: BG,
      },
      allowBackup: false,
      softwareKeyboardLayoutMode: "resize",
      predictiveBackGestureEnabled: false,
      permissions: [
        "android.permission.INTERNET",
        "android.permission.POST_NOTIFICATIONS",
        "com.google.android.gms.permission.AD_ID",
        "android.permission.VIBRATE",
      ],
      blockedPermissions: [
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.SYSTEM_ALERT_WINDOW",
      ],
      // App Links only on prod: the dev app must not claim ezysplit.arun.codes.
      intentFilters: IS_DEV
        ? []
        : [
            {
              action: "VIEW",
              autoVerify: true,
              data: [
                {
                  scheme: "https",
                  host: "ezysplit.arun.codes",
                  pathPrefix: "/app",
                },
                {
                  scheme: "http",
                  host: "ezysplit.arun.codes",
                  pathPrefix: "/app",
                },
              ],
              category: ["BROWSABLE", "DEFAULT"],
            },
          ],
    },
    extra: {
      appVariant: IS_DEV ? "development" : "production",
      googleWebClientId: googleWebClientId(),
    },
    plugins: [
      "@react-native-firebase/app",
      "@react-native-firebase/crashlytics",
      [
        "@react-native-firebase/messaging",
        {
          android: {
            // drawable + color are created by plugins/withEzySplitAndroid.js
            notificationIcon: "./assets/notification-icon/xxxhdpi.png",
            notificationColor: "#3ECF8E",
          },
        },
      ],
      "@react-native-google-signin/google-signin",
      [
        "expo-build-properties",
        {
          android: {
            minSdkVersion: 26,
            targetSdkVersion: 36,
            enableMinifyInReleaseBuilds: true,
            enableShrinkResourcesInReleaseBuilds: true,
          },
          ios: {
            // RNFirebase on iOS needs static frameworks; with use_frameworks
            // React Native is compiled from source instead of the
            // precompiled xcframeworks (slower first build, but compatible).
            useFrameworks: "static",
            buildReactNativeFromSource: true,
          },
        },
      ],
      ["expo-font", { fonts: FONTS }],
      [
        "expo-splash-screen",
        {
          image: "./assets/icon.png",
          imageWidth: 160,
          resizeMode: "contain",
          backgroundColor: BG,
        },
      ],
      "expo-sharing",
      "./plugins/withEzySplitAndroid",
      "./plugins/withEzySplitSigning",
    ],
  },
};

export default config;
