export enum Routes {
  Login = 'Login',
  PrivacyPolicy = 'PrivacyPolicy',
  ForgetPassword = 'ForgetPassword',
  OtpVerification = 'OtpVerification',
  SignUp = 'SignUp',
  Home = 'Home',
  About = 'About',
  Tab = 'Tab',
  Notification = 'Notification',
  Transaction = 'Transaction',
  TabTransaction = 'TabTransaction',
  BalanceHistory = 'BalanceHistory',
  ReceivePayment = 'ReceivePayment',
  TransactionHistory = 'TransactionHistory',
  AddAccount = 'AddAccount',
  VerifyEmail = 'VerifyEmail',
  QRScanner = 'QRScanner',
  Paynow = 'Paynow',
  Profile = 'Profile',
  BankList = 'BankList',
}
